#include "chototsuPlayer.hpp"
#include "humanPlayer.hpp"
#include "randomPlayer.hpp"
#include "MyPlayer.hpp"
#include "MyPlayer1.hpp"
#include "MonteCarloPlayerSample.hpp"
#include "MonteCarloPlayer1.hpp"